name: prec-res
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11

  # Core
  - numpy
  - pandas

  # Gridded data
  - xarray
  - rioxarray
  - xesmf
  - xhistogram
  - dask
  - distributed

  # I/O backends for xarray
  - netcdf4
  - h5netcdf

  # Plotting
  - matplotlib
  - seaborn
  - cartopy

  # Notebooks
  - jupyterlab
  - ipykernel
